server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        # 核心魔法：找不到路径时，统统返回 index.html 交给 React Router 处理
        try_files $uri $uri/ /index.html;
    }
}